Support build postgis on rhel8
rhel8 is using system gcc which is 8.5.0, need tofix following compiling error
error: 'strncpy' specified bound depends on the length of the source argument.
error: this statement may fall through [-Werror=implicit-fallthrough=]

[GPR-626]

Authored-by: Shaoqi Bai <bshaoqi@vmware.com>